// Generated by LiveScript 1.5.0
var htmlWebpackPlugin, htmlWebpackInlineSourcePlugin, path, uglifyjsWebpackPlugin, webpack;
htmlWebpackPlugin = require('html-webpack-plugin');
htmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin');
path = require('path');
uglifyjsWebpackPlugin = require('uglifyjs-webpack-plugin');
webpack = require('webpack');
module.exports = {
  mode: 'none',
  entry: './src/index.ls',
  output: {
    path: path.join(__dirname, '.'),
    filename: 'index.min.js'
  },
  module: {
    rules: [
      {
        test: /\.ls$/,
        exclude: /node_modules/,
        use: ['babel-loader', 'livescript-loader']
      }, {
        test: /\.css$/,
        exclude: /node_modules/,
        use: 'style-loader'
      }
    ]
  },
  plugins: [
    new htmlWebpackPlugin({
      title: '[ The Tap ]',
      cache: false,
      minify: {
        collapseWhitespace: true
      },
      hash: true,
      inlineSource: /.css$/
    }), new htmlWebpackInlineSourcePlugin()
  ],
  resolveLoader: {
    modules: [path.join(__dirname, 'node_modules')]
  },
  resolve: {
    modules: [path.join(__dirname, 'node_modules')],
    extensions: ['.ls', '.js']
  }
};
